remote_install/controllers/component.py
#
# component.py - Interface to add and edit most of the "components"
#
# Copyright 2011, Red Hat, Inc
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Authors:
#   Tim Flink <tflink@redhat.com>


from flask import Blueprint, request, render_template, url_for, redirect, flash
from flaskext.login import current_user
from remote_install import app, db
from remote_install.view.create_component_api import CreateInstallerApi, CreateUserApi, CreateMachineTemplateApi, CreateMachineSlotApi
from remote_install.view.view_component_api import ViewUserApi, ViewMachineTemplateApi, ViewInstallerApi, ViewMachineApi, ViewMachineSlotApi
from remote_install.models.machine import Machine
from remote_install.models.user import User

import remote_install.controllers.job

component = Blueprint('component', __name__)

@component.before_request
def restrict_components_to_users():
    if not current_user.is_authenticated():
        return app.login_manager.unauthorized()

@component.route('/')
def index():
    if app.debug:
        app.logger.debug('rendering index')
    return render_template('main.html')

# endpoints for creating new components
component.add_url_rule('/component/installer/new', 'new_installer',
                        view_func=CreateInstallerApi.as_view('installer'))
component.add_url_rule('/component/machine_template/new', 'new_machine_template',
                        view_func=CreateMachineTemplateApi.as_view('machine_template'))
component.add_url_rule('/component/user/new', 'new_user',
                        view_func=CreateUserApi.as_view('user'))
component.add_url_rule('/component/machine_slot/new', 'new_machine_slot',
                        view_func=CreateMachineSlotApi.as_view('machine_slot'))

# this consolidates the paging boilerplate for the view functions into a single
# function
def register_view_api(view, endpoint, url, pk='id', pk_type='int', default=None):
    view_func = view.as_view(endpoint)
    component.add_url_rule(url, defaults={pk:default}, view_func = view_func,
                            methods=['GET'])
    component.add_url_rule('%spage/<%s:%s>' %(url, pk_type, pk),
                            view_func=view_func,methods=['GET'])

# endpoints for the view functions
register_view_api(ViewUserApi, 'show_users', '/component/user/', pk='page', default=1)
register_view_api(ViewMachineTemplateApi, 'show_machine_templates',
                    '/component/machine_template/', pk='page', default=1)
register_view_api(ViewInstallerApi, 'show_installers', '/component/installer/',
                    pk='page', default=1)
register_view_api(ViewMachineApi, 'show_machines', '/component/machine/', pk='page', default=1)
register_view_api(ViewMachineSlotApi, 'show_machine_slots',
                    '/component/machine_slot/', pk='page', default=1)

@component.route('/component/user/<int:user_id>', methods = ['POST'])
def process_user(user_id):
    if not current_user.admin:
        flash('You need admin priviliges to make changes')
        return redirect(url_for('.show_users'))

    user = User.query.get(user_id)
    if user and request.form['request']:
        if request.form['request'] == 'MAKE_ADMIN':
            user.admin = True
        elif request.form['request'] == 'REMOVE_ADMIN':
            user.admin = False
        else:
            flash('Invalid Request: %s' % request.form['request'])
            redirect(url_for('.show_users'))
        db.session.add(user)
        db.session.commit()
        flash('Request %s for user %s Succeeded.' % (request.form['request'], user.username))
        return redirect(url_for('.show_users'))

@component.route('/component/machine/<int:machine_id>', methods = ['GET', 'POST'])
def machine_detail(machine_id):
    if request.method == 'GET':
        if app.debug:
            app.logger.debug('rendering detail for machine %d' % machine_id)

        machine = Machine.query.get_or_404(machine_id)
        return render_template('detail_machine.html', machine = machine)

    if request.method == 'POST':
        if app.debug:
            app.logger.debug('machine %d received POST request %s' % (machine_id, str(request.form)))

        if request.form['request']:
            if request.form['request'] == 'STOP':
                app.logger.info('Stopping machine %d' % machine_id)
                machine = Machine.query.filter_by(id=machine_id).first()

                machine_control = remote_install.controllers.job.get_machine_control()
                machine_control.stop_machine(machine.name)

                machine.status = 'STOPPED'
                db.session.add(machine)
                db.session.commit()

            if request.form['request'] == 'DELETE':
                app.logger.info('Deleting machine %d' % machine_id)
                machine = Machine.query.filter_by(id=machine_id).first()

                machine_control = remote_install.controllers.job.get_machine_control()
                machine_control.delete_machine(machine.name)
                machine_control.delete_disk(machine.name)

                machine.status = 'DELETED'
                db.session.add(machine)
                db.session.commit()

        return render_template('detail_machine.html', machine = machine)

remote_install/controllers/job.py
#
# job.py - interface for creating, viewing and changing job-related data
#
# Copyright 2011, Red Hat, Inc
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Authors:
#   Tim Flink <tflink@redhat.com>


from flask import Blueprint, render_template, request, redirect, url_for, flash
from flaskext.login import login_required, current_user
from sqlalchemy import desc
from remote_install.models.job import Job
from remote_install import db, app
import os
from remote_install.machine_control import FabricController
from remote_install.machine_control.stub import StubMachineControl
from remote_install.models.installer import Installer
from remote_install.models.machine import MachineTemplate, Machine, MachineSlot
from remote_install.models.user import User

jobs = Blueprint('job', __name__)

@jobs.route('/job/', defaults={'page': 1})
@jobs.route('/job/page/<int:page>', methods = ['GET'])
def show_jobs(page):
    job_paginate = Job.query.order_by(desc('id')).paginate(page, per_page=10)
    return render_template('view/view_jobs.html', paginate = job_paginate)


@jobs.route('/job/mine', defaults={'page': 1})
@jobs.route('/job/mine/page/<int:page>', methods = ['GET'])
@login_required
def show_my_jobs(page):
    job_paginate = Job.query.filter_by(user=current_user).order_by(desc('id')).paginate(page, per_page=10)
    return render_template('view/view_jobs.html', paginate = job_paginate)

@jobs.route('/job/new', methods = ['GET', 'POST'])
@login_required
def new_job():
    if request.method == 'GET':
        slots = MachineSlot.query.filter_by(active=False).all()
        if not len(slots) > 0:
            app.logger.info('All slots are currently full')
            flash('No slots are currently available, please try again later')
            return redirect(url_for('main.index'))
        else:
            app.logger.info('There are currently %d slots available' % len(slots))
            flash('There are currently %d slots available' % len(slots))

        users = User.query.all()
        templates = MachineTemplate.query.all()
        installers = Installer.query.all()
        return render_template('create/create_job.html', users=users, templates=templates, installers=installers)

    elif request.method == 'POST':
        slots = MachineSlot.query.filter_by(active=False).all()
        if not len(slots) > 0:
            app.logger.info('All slots are currently full')
            flash('No slots are currently available, please try again later')
            return redirect(url_for('main.index'))

        # grab data out of the POST form
        template = MachineTemplate.query.filter(MachineTemplate.id == request.form['template']).first()
        installer = Installer.query.filter(Installer.id == request.form['installer']).first()

        # setup slot and job
        if app.debug:
            app.logger.debug('Reserving slot %d and creating skeleton job' % slots[0].id)

        slot = slots[0]
        slot.active = True

        job = Job('newjob', current_user, 'INITIALIZING', None)
        db.session.add(slot)
        db.session.add(job)
        db.session.commit()

        if app.debug:
            app.logger.debug('Skeleton job %d created ' % job.id)


        machine_name = 'test-%d' % job.id
        machine = Machine(machine_name, template, installer, 'INIT', slot)

        job.machine = machine
        job.name = "job-%d" % job.id
        db.session.add(machine)
        db.session.add(job)
        db.session.commit()

        app.logger.info('Creating new virtual machine for job %d' % job.id)

        # create the machine
        machine_control = get_machine_control()
        kickstart = 'http://%s:%d/job/%d/kickstart' % \
                    (app.config['KICKSTART_SERVER'],
                        app.config['KICKSTART_PORT'], job.id)
        if app.debug:
            app.logger.debug('creating new machine %s' % machine_name)

        logs =  machine_control.create_machine(machine_name,
                                    template,installer, slot, kickstart)

        # finish up the metadata
        app.logger.info('Machine %s created' % machine.name)

        machine.status = 'RUNNING'
        db.session.add(machine)
        db.session.commit()

        return redirect(url_for('.job_detail', job_id=job.id))


def get_machine_control():
    if os.getenv('TEST') == 'yes' or app.config['FAKE_MACHINE'] == True:
        return StubMachineControl()
    else:
        return FabricController()


@jobs.route('/job/<int:job_id>', methods = ['GET', 'POST'])
def job_detail(job_id):

    job = Job.query.get_or_404(job_id)
    if job.status == 'INITIALIZING':
        flash('The job has been created and is currently initializing. Once ' \
                'initialization is complete, this page will show login information. ' \
                'Please wait about 30 seconds and refresh the page manually.')

    if request.method == 'GET':
        if app.debug:
            app.logger.debug('rendering detail for job %d' % job_id)

        log_files = []
        try:
            log_files = os.listdir('%s/test-%d' % (app.config['LOG_LOCATION'], job.id))
        except OSError:
            app.logger.warn('No logs found for job %d' % job.id)

        # if the job isn't running, don't bother getting the slot information
        slot = None
        if job.status in ['RUNNING', 'INSTALLING']:
            slot = job.machine.slot

        return render_template('detail_job.html', job = job,
                                log_prefix = app.config['LOG_PREFIX'],
                                logs = log_files, slot=slot)

    if request.method == 'POST':
        if not (current_user.admin or current_user.get_id() == job.user.id):
            app.logger.warn('User %s (id: %d) tried to modify job %d (owner: %s, id: %d)' %
                    (current_user.username, current_user.get_id(), job.id, job.user.username, job.user.id))
            flash('You need admin priviliges to make changes to this job.')
            return redirect(url_for('job.job_detail', job_id=job_id))

        if app.debug:
            app.logger.debug('job %d received POST request %s' % (job_id, str(request.form)))

        if request.form['request']:
            machine_control = get_machine_control()

            if request.form['request'] == 'COMPLETE':
                app.logger.info('Completing job %d' % job_id)
                job.status = 'COMPLETE'
                job.machine.slot.active = False

                # now shutdown and delete the VM
                if job.machine.status not in ['STOPPED', 'DELETED']:
                    machine_control.stop_machine(job.machine.name)
                    job.machine.status = 'STOPPED'
                if job.machine.status != 'DELETED':
                    machine_control.delete_machine(job.machine.name)
                    machine_control.delete_disk(job.machine.name)
                    job.machine.status = 'DELETED'

                db.session.add(job)
                db.session.add(job.machine.slot)
                db.session.add(job.machine)
                db.session.commit()

            if request.form['request'] == 'RESTART':
                machine_control.start_machine(job.machine.name)
                job.machine.status = 'RUNNING'
                db.session.add(job.machine)
                db.session.commit()


        return redirect(url_for('.job_detail', job_id=job_id))


@jobs.route('/job/<int:job_id>/init_done', methods = ['GET'])
def complete_job_init(job_id):
    job = Job.query.get(job_id)
    job.status = 'INSTALLING'
    db.session.add(job)
    db.session.commit()
    return "OK"


@jobs.route('/job/<int:job_id>/install_done', methods = ['GET'])
def complete_job_installing(job_id):
    job = Job.query.get(job_id)
    job.status = 'RUNNING'

    # one artifact of using virt-install is that it doesn't allow for restarting
    # after anaconda is done, QND fix is to mark the machine stopped and allow
    # for manual restarting

    job.machine.status = 'STOPPED'
    db.session.add(job)
    db.session.add(job.machine)
    db.session.commit()
    return "OK"


@jobs.route('/job/<int:job_id>/kickstart', methods = ['GET'])
def get_kickstart(job_id):
    job = Job.query.get(job_id)
    server = app.config['KICKSTART_SERVER']
    port = app.config['KICKSTART_PORT']
    password = job.machine.slot.password
    tree = job.machine.installer.location
    job_num = job.id
    return render_template('kickstart/base.ks', password=password, tree=tree,
                            job_num = job_num, server=server, port=port)

remote_install/controllers/main.py
#
# main.py - interface for login, logout and the main page
#
# Copyright 2011, Red Hat, Inc
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Authors:
#   Tim Flink <tflink@redhat.com>


from remote_install import app, db, login_manager
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flaskext.login import login_user, logout_user, login_required, current_user, AnonymousUser
import datetime

from remote_install.models.user import User

main = Blueprint('main', __name__)


@login_manager.user_loader
def load_user(userid):
    user = User.query.get(userid)
    if user:
        return user
    else:
        return AnonymousUser

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')

    elif request.method == 'POST':
        user = User.query.filter_by(username=request.form['username']).first()
        if user and user.check_password(request.form['password']):
            # refresh last auth time since it's used to check login
            user.lastauth = datetime.datetime.now()
            db.session.add(user)
            db.session.commit()
            login_user(user)

            app.logger.info('Successful login for user %s' % request.form['username'])
            flash('Logged In Successfully!')
            return redirect(request.args.get('next') or url_for('.index'))
        else:
            app.logger.info('FAILED login for user %s' % request.form['username'])
            flash('Login Failed! Please Try again!')
            return render_template('login.html')

@main.route('/logout')
@login_required
def logout():
    current_user.lastauth = None
    db.session.add(current_user)
    db.session.commit()
    logout_user()
    return redirect(url_for('.index'))

@main.route('/')
def index():
    if app.debug:
        app.logger.debug('rendering index')
    return render_template('main.html')

remote_install/templates/admin_toolbar.html
<h3>Create</h3>
<ul>
    <li> <a href="{{ url_for('component.new_user') }}"> new user </a> </li>
    <li> <a href="{{ url_for('component.new_machine_template') }}"> new machine template </a> </li>
    <li> <a href="{{ url_for('component.new_machine_slot') }}"> new machine slot </a> </li>
    <li> <a href="{{ url_for('component.new_installer') }}"> new installer </a> </li>
</ul>

<h3>Show</h3>
<ul>
    <li> <a href="{{ url_for('component.show_users') }}"> users </a> </li>
    <li> <a href="{{ url_for('component.show_machine_templates') }}"> machine templates </a> </li>
    <li> <a href="{{ url_for('component.show_machine_slots') }}"> machine slots </a> </li>
    <li> <a href="{{ url_for('component.show_installers') }}"> installers </a> </li>
    <li> <a href="{{ url_for('component.show_machines') }}"> machines </a> </li>
</ul>

remote_install/templates/detail_job.html
{% extends "layout.html" %}


{% block header %}
<h1> Job {{ job.id }} </h1>
{% endblock %}

{% block body %}

{% if job.status in ['INSTALLING', 'RUNNING'] and (current_user.get_id() == job.user.id or current_user.admin) %}
<h3> Logging in to the Virtual Machine </h3>
<p>
The virtual machine is now running. You can log in to it by clicking on the
'Remote Access' link below and logging in using either username and the
password listed below.
</p>

<p>
When testing is complete, please kill the VM by clicking on the
'Complete Job and Kill VM\' button below
</p>
{% endif %}

<table class="listtable">
    <tr>
        <th>ID</td>
        <td>{{ job.id }}</td>
    </tr>
    <tr>
        <th>user</td>
        <td>{{ job.user.username }}</td>
    </tr>
    <tr>
        <th>name</td>
        <td>{{ job.name }}</td>
    </tr>
    <tr>
        <th>status</td>
        <td>{{ job.status }}</td>
    </tr>
    <tr>
        <th>machine</td>
        <td><a href="{{ url_for('component.machine_detail', machine_id=job.machine.id) }}">
                {{ job.machine.name }} </a></td>
    </tr>
    {% if job.status in ['RUNNING', 'INSTALLING'] %}
    <tr>
        <th>Access Info</td>
        <td>
            <table>
                <tr>
                    <td>URL</td>
                    <td><a href="{{ slot.url }}" target="_blank"> Remote Access </a></td>
                </tr>
                <tr>
                    <td>VNC User (Faster)</td>
                    <td>{{ slot.username }}</td>
                </tr>
                <tr>
                    <td>QEMU Console User</td>
                    <td>{{ slot.username }}-detail</td>
                </tr>
                <tr>
                    <td>Password</td>
                    <td>{{ slot.password }}</td>
                </tr>
            </table>
        </td>
    </tr>
    {% endif %}


    {% if job.status != 'INITIALIZING' %}
    <tr>
        <th> Log Files </td>
        <td>
            <table>
                {% for log in logs %}
                    <tr>
                        <td> <a href="{{ log_prefix}}/{{job.machine.name}}/{{ log }}" target="_blank"> {{ log }} </a> </td>
                    </tr>
                {% endfor %}
            </table>
        </td>
    </tr>
    {% endif %}
</table>

{% if job.status != 'COMPLETE' %}
<br>
<br>
<table>
    <tr>
        {% if current_user.get_id() == job.user.id or current_user.admin %}
        <td>
            <form method='post' action='./{{ job.id }}'>
                <input type='hidden' name='request' value='COMPLETE'/>
                <input type='submit' value='Complete job and kill VM'/>
            </form>
        </td>
        {% endif %}
        {% if current_user.admin and job.status == 'INITIALIZING' %}
        <td>
            <form method='get' action='./{{ job.id }}/init_done'>
                <input type='submit' value='Force change to INSTALLING'/>
            </form>
        </td>
        {% endif %}
        {% if current_user.admin and job.status == 'INSTALLING' %}
        <td>
            <form method='get' action='./{{ job.id }}/install_done'>
                <input type='submit' value='Force INSTALLING complete'/>
            </form>
        </td>
        {% endif %}
        {% if (current_user.admin or job.user == current_user) and job.machine.status == 'STOPPED' %}
        <td>
            <form method='post' action='./{{ job.id }}'>
                <input type='hidden' name='request' value='RESTART'/>
                <input type='submit' value='Start VM'/>
            </form>
        </td>
        {% endif %}

    </tr>

</table>
{% endif %}

{% endblock%}

remote_install/templates/detail_machine.html
{% extends "layout.html" %}


{% block header %}
<h1>Machine {{ machine.name }}</h1>
{% endblock %}

{% block body %}


<table class="listtable">
    <tr>
        <th>ID</td>
        <td>{{ machine.id }}</td>
    </tr>
    <tr>
        <th>template</td>
        <td>{{ machine.template.name }}</td>
    </tr>
    <tr>
        <th>name</td>
        <td>{{ machine.name }}</td>
    </tr>
    <tr>
        <th>installer</td>
        <td>{{ machine.installer.name }}</td>
    </tr>
    <tr>
        <th>status</td>
        <td>{{ machine.status }}</td>
    </tr>
    <tr>
        <th>slot</td>
        <td>{{ machine.slot.id }} </td>
</table>


{% if machine.status != 'DELETED' %}
<br>

<table>
    <tr>
    {% if machine.status == 'RUNNING' %}
        <td>
            <form method='post' action='./{{ machine.id }}'>
                <input type='hidden' name='request' value='STOP'/>
                <input type='submit' value='Stop Machine'/>
            </form>
        </td>
    {% endif %}
    {% if machine.status == 'STOPPED' %}
        <td>
            <form method='post' action='./{{ machine.id }}'>
                <input type='hidden' name='request' value='DELETE'/>
                <input type='submit' value='Delete Machine'/>
            </form>
        </td>
    {% endif %}

    </tr>

</table>
{% endif %}

{% endblock%}

remote_install/templates/formbase.html
{% extends "layout.html" %}

{% block header %}
<h1> Add {{ form_type }} </h1>
{% endblock %}

{% block body %}
<form method="post" action="new">
    <!-- <form method="post" action="{{ action_type }}"> -->
    <table>
    {% block form %}
    form goes here!
    {% endblock %}
        <tr>
            <td>
                <input type="submit" value="Create new {{ form_type }}"/>
            </td>
        </tr>
    <table>
</form>
{% endblock %}

remote_install/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{{ title }}</title>
  <meta name="description" content="{{ meta_description }}">
  <meta name="author" content="{{ meta_author }}">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <!-- CSS: implied media=all -->
  <!-- CSS concatenated and minified via ant build script-->
  <!-- <link rel="stylesheet" href="css/style.css"> -->
  <link rel="stylesheet" href=" {{ url_for('static', filename='css/style.css') }} ">
  <link rel="stylesheet" href=" {{ url_for('static', filename='css/960.css') }} ">
  <!-- end CSS-->
</head>

{% macro render_pagination(pagination, endpoint) %}
<div class=pagination>
    {% if pagination.has_prev %}
        <a href="{{ url_for(endpoint, page=(pagination.page - 1)) }}">&laquo; Prev</a>
    {% endif %}
    {% for page in pagination.iter_pages() %}
        {% if page %}
            {% if page != pagination.page %}
                <a href="{{ url_for(endpoint, page=page) }}"> {{ page }}</a>
            {% else %}
                <strong> {{ page }} </strong>
            {% endif %}
        {% else %}
            <span class=ellipsis>...</span>
        {% endif %}
    {% endfor %}

    {% if pagination.has_next %}
        <a href="{{ url_for(endpoint, page=(pagination.page + 1)) }}"> Next &raquo;</a>
    {% endif %}
</div>
{% endmacro %}


<body>

    <div id="container" class="container_12">
        <div id="banner" class="grid_12">
            <img src=" {{ url_for('static', filename='images/remote_install_banner.png') }} "/>
        </div>
        <div class="clear"></div>
        <div class="grid_3" id="toolbar">

            {% if current_user.is_authenticated() %}
            <p>
                Welcome {{ current_user.username }}.
                <a href="{{ url_for('main.logout') }}"> Logout</a>
            </p>

            <form method='get' action='{{ url_for('job.new_job') }}'>
                <input type='submit' value='New Job'/>
            </form>

            <h3> View Jobs </h3>
            <ul>
                <li> <a href="{{ url_for('job.show_my_jobs') }}"> my jobs </a> </li>
                <li> <a href="{{ url_for('job.show_jobs') }}"> all jobs </a> </li>
            </ul>

            {% if current_user.admin %}
                {% include 'admin_toolbar.html' %}
            {% endif %}

            <br>
            <br>

            <img src=" {{ url_for('static', filename='images/powered_by_fedora.png') }} "/>
            {% else %}
            <p>
            <a href="{{ url_for('main.login') }}"> Login </a>
            </p>

            <h3> View Jobs </h3>
            <ul>
                <li> <a href="{{ url_for('job.show_jobs') }}"> all jobs </a> </li>
            </ul>
            {% endif %}
        </div>

        <div class="grid_9" id="main">
            <header>

            {% block header %}
            header goes here
            {% endblock %}
            </header>

            <div id="main" role="main">

                {% for message in get_flashed_messages() %}
                    <div class=flash>{{ message }}</div>
                {% endfor %}

                {% block body %}
                body goes here
                {% endblock %}
            </div>

            <!-- I'm pretty sure that I don't want a footer
            <footer>

            {% block footer %}
            footer goes here
            {% endblock %}

            </footer>
            -->
        </div> <!--! end of #main -->
    </div> <!-- end of container_12 -->


  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->
  
</body>
</html>

remote_install/templates/login.html
{% extends "layout.html" %}


{% block header %}
<h1> Login </h1>
{% endblock %}

{% block body %}

<form method="post" action="login">
    <table>
        <tr>
            <th>Username</th>
            <td> <input type="text" name="username" value="user"/> </td>
        </tr>
        <tr>
            <th>Password</th>
            <td> <input type="password" name="password" value="password"/> </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Login"/>
            </td>
        </tr>
    <table>
</form>

{% endblock%}

remote_install/templates/main.html
{% extends "layout.html" %}

{% block header %}
{% endblock %}

{% block body %}

    <h2> Welcome </h2>
    <p>
        This application supports the remote testing of Fedora's
        Grapical installation.
    </p>

    <p>
    This allows you to try a custom installation of Fedora in a remote virtual 
    machine without needing to download ISOs or use your own hardware. Play with
    the interface, try as many different installations as you would like and if
    you do hit issues, please report them
    <a href="http://supermegawaffle.com/remote_install/issues.html"> at the project
        site</a>.
    </p>

    <h2> WARNING</h2>
    <p>
    This application is <b>ONLY</b> a demo, it might (and probably will) break.
    If you do hit a bug, please file an issue at
    <a href="http://supermegawaffle.com/remote_install/issues.html"> the project
        site</a>.
    </p>

    <h2>Basic Usage Instructions</h2>
    <p>
    <ul>
        <li>
            To get started, create a new job using the button in the upper left
            hand side of the page. VM creation is currently very slow, please wait until
            the page has reloaded after job creation before clicking anything else.
        </li>
        <li>
            Once the page has reloaded, initialization of the job will take 30 
            seconds to one minute. The job detail page will change (manual refresh required)
            when initialization is complete and login instructions will be displayed.
        </li>
        <li>
            Login to the virtual machine by clicking on the 'remote access' link
            on the page and logging in to the virtual machine's VNC console.
        </li>
        <li>
            Once installation is complete, you will need to reboot the VM from
            this web UI before logging in to the installed machine.
        </li>
    </ul>
    </p>



{% endblock %}